name: Multiple Jobs Workflow

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: echo "Building application..."

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests..."

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Security scan
        run: echo "Running security scan..."

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - security-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy application
        run: echo "Deploying application..."
